### PR TITLE
Rework config options

### PR DESCRIPTION
**Pull request by werdeil**
Hey @DJ-Dingo here is the rework to avoid having 13 options for 4 lines.

Now for each line we have a text option and and a type option
- Text field is open, and can be configured in the menu
- Type shall be in ['Taken_Photo', 'Printed', 'Forgotten', 'Remaining_Duplicates', 'Date_Time', 'Text'] and cn also be configured through the menu.

Tell me if you find it easier to understand than the actual solution.

As for previous PR, I haven't tested it and I'm sure I made mistakes, good luck on the test.

### CODE REVIEW

**Comment by DJ-Dingo** [comment]
Nope

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
[ INFO    ] pibooth           : Installed plugins: picture-template-0.0.3, extra-lights-1.0.1, sound-effects-0.0.3, lcd_i2c_werdeil4-1.1.2
[ INFO    ] pibooth           : Starting the photo booth application on Raspberry pi 3B
[ INFO    ] pibooth           : Configuring Picamera camera ...
[ WARNING ] pibooth           : No printer found (pycups or pycups-notify not installed)
[ ERROR   ] pibooth           : 'PiApplication' object has no attribute 'taken_photo_text'
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pibooth/booth.py", line 343, in main_loop
    self._pm.hook.pibooth_startup(cfg=self._config, app=self)
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/pi/.local/lib/python3.7/site-packages/pibooth/plugins/pibooth_lcd_i2c_werdeil4.py", line 118, in pibooth_startup
    write_lcd_lines(app)
  File "/home/pi/.local/lib/python3.7/site-packages/pibooth/plugins/pibooth_lcd_i2c_werdeil4.py", line 65, in write_lcd_lines
    app.lcd.write_string(app.taken_photo_text[:app.cols - 4])
AttributeError: 'PiApplication' object has no attribute 'taken_photo_text'
[ ERROR   ] pibooth           : system='Linux', node='raspberrypi', release='5.4.72-v7+', version='#1356 SMP Thu Oct 22 13:56:54 BST 2020', machine='armv7l', processor=''
 ***********************************************************************************
 *                     Oops! It seems that pibooth has crached                     *
 *     You can report an issue on https://github.com/pibooth/pibooth/issues/new    *
 *                       and post the file: /tmp/pibooth.log                       *
 *******************************************************************************

**Comment by werdeil** [comment]
Damn dummy copy/paste mistake again...

**Comment by DJ-Dingo** [comment]
:-) yeah we love and hate copy/paste.. hehe

You can't have text on line 3 and 4 when you have and 16x2 

(2 and 3 on lcd) 
lcd line 1 = 0, line 2 = 1 line 3 = 2, line 4 = 3) 

It says that there is something on line 2( line 3 in the config.cfg)
It has to be empty on a 16x2

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
[ INFO    ] pibooth           : Installed plugins: lcd_i2c_werdeil4-1.1.2, extra-lights-1.0.1, sound-effects-0.0.3, picture-template-0.0.3
[ INFO    ] pibooth           : Starting the photo booth application on Raspberry pi 3B
[ INFO    ] pibooth           : Configuring Picamera camera ...
[ WARNING ] pibooth           : No printer found (pycups or pycups-notify not installed)
[ ERROR   ] pibooth           : Cursor position (2, 0) invalid on a 2x16 LCD.
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pibooth/booth.py", line 343, in main_loop
    self._pm.hook.pibooth_startup(cfg=self._config, app=self)
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/pi/.local/lib/python3.7/site-packages/pibooth/plugins/pibooth_lcd_i2c_werdeil4.py", line 126, in pibooth_startup
    write_lcd_lines(app)
  File "/home/pi/.local/lib/python3.7/site-packages/pibooth/plugins/pibooth_lcd_i2c_werdeil4.py", line 63, in write_lcd_lines
    app.lcd.cursor_pos = (line_index, 0)
  File "/usr/local/lib/python3.7/dist-packages/RPLCD/lcd.py", line 155, in _set_cursor_pos
    raise ValueError(msg.format(pos=value, lcd=self.lcd))
ValueError: Cursor position (2, 0) invalid on a 2x16 LCD.
[ ERROR   ] pibooth           : system='Linux', node='raspberrypi', release='5.4.72-v7+', version='#1356 SMP Thu Oct 22 13:56:54 BST 2020', machine='armv7l', processor=''
 ***********************************************************************************
 *                     Oops! It seems that pibooth has crached                     *
 *     You can report an issue on https://github.com/pibooth/pibooth/issues/new    *
 *                       and post the file: /tmp/pibooth.log                       *
 ***********************************************************************************

**Comment by werdeil** [comment]
Indeed, I was wondering how it would work on 2 line LCD, thought I didn't change from the previous behavior but in fact I had.

I'm now using the lcd_rows setting to avoid going into line 3 if there are only 2.

**Comment by DJ-Dingo** [comment]
in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/pi/.local/lib/python3.7/site-packages/pibooth/plugins/pibooth_lcd_i2c_werdeil4.py", line 127, in pibooth_startup
    write_lcd_lines(app)
  File "/home/pi/.local/lib/python3.7/site-packages/pibooth/plugins/pibooth_lcd_i2c_werdeil4.py", line 62, in write_lcd_lines
    for row_index in range(app.lcd_rows):
AttributeError: 'PiApplication' object has no attribute 'lcd_rows'
[ ERROR   ] pibooth           : system='Linux', node='raspberrypi', release='5.4.72-v7+', version='#1356 SMP Thu Oct 22 13:56:54 BST 2020', machine='armv7l', processor=''
 ****************************************************************************

**Comment by werdeil** [comment]
Another fix, another try...

**Comment by DJ-Dingo** [comment]
:-) 

 in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/pi/.local/lib/python3.7/site-packages/pibooth/plugins/pibooth_lcd_i2c_werdeil5.py", line 119, in pibooth_startup
    write_lcd_lines(app)
  File "/home/pi/.local/lib/python3.7/site-packages/pibooth/plugins/pibooth_lcd_i2c_werdeil5.py", line 62, in write_lcd_lines
    for row_index in range(app.rows):
TypeError: 'str' object cannot be interpreted as an integer
[ ERROR   ] pibooth           : system='Linux', node='raspberrypi', release='5.4.72-v7+', version='#1356 SMP Thu Oct 22 13:56:54 BST 2020', machine='armv7l', processor=''

**Comment by DJ-Dingo** [comment]
This does the job
for row_index in range(int(app.rows)):

**Comment by DJ-Dingo** [comment]
Hi @werdeil  

The only thing I miss is that it remembers the text for the different choices. No one can remember etc. Date-time combination if they delete it to write text instead..

And since we have cols and rows in the menu, we should allso have the lcd_port_address = 0x3F, as this is the function you are going to change if you e.g. changes screen / port expander, they often have a new address (or you can hardcode a new address as i mention in the readme file)
. 
I can test tomorrow with another port expander that has a different address to see how it responds.

But i love the menu part (see pics), it works, I have not tested all combinations, yet, but i will.. :-) 

 lcd_i2c_menu
menu

**Pull request merged**
