### PR TITLE
Refactoring of the plugin

### PR DESCRIPTION
**Pull request by werdeil**
Hi @DJ-Dingo,

In order to understand well how the plugin work I did some refactoring to simplify the code. I hope it will be more readable for you too.

As I can't test it I rely on you. As there is a lot of code change I hope everything will still work.

There is only one behavior change: if you change something on the config while pibooth is opened it shall only be taken into account when you re-entrer the wait state. I think this is not an issue but tell me if you disagree.

### CODE REVIEW

**Comment by DJ-Dingo** [comment]
Don't work.

I like that the code is more simpel, I tried to do that myself but could not make it work.
So i did it the way I used to, when I had to do something with LCD.

I wanted to make shure that it understands if it is a 16 or 20 lcd(or something else), or if it had 1, 2 or 4 lines(or more) on the lcd.
And that i could use other combination of lcd's and cheat it to use them too. 
And importen that it would only show text like "Taken Photo bla bla bla" until the counter and not overwrite the counter, if you write more text.   

 Looks like you got all that :-)

But can't see where you get the text from, remaining_duplicates, Printed, forgotten
maybe that should be from line 178..??

And good with the re-entrer the wait state. So you can change text when pibooth i running.
Especially if we one day will be able to change plugins config from menu.


pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
[ INFO    ] pibooth           : Installed plugins: extra-lights-1.0.1, sound-effects-0.0.3, picture-template-0.0.3, lcd_i2c_werdeil-1.1.0
[ INFO    ] pibooth           : Starting the photo booth application on Raspberry pi 3B
[ INFO    ] pibooth           : Configuring Picamera camera ...
[ WARNING ] pibooth           : No printer found (pycups or pycups-notify not installed)
[ ERROR   ] pibooth           : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pibooth/booth.py", line 343, in main_loop
    self._pm.hook.pibooth_startup(cfg=self._config, app=self)
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/pi/.local/lib/python3.7/site-packages/pibooth/plugins/pibooth_lcd_i2c_werdeil.py", line 189, in pibooth_startup
    write_photo_count(app)
  File "/home/pi/.local/lib/python3.7/site-packages/pibooth/plugins/pibooth_lcd_i2c_werdeil.py", line 81, in write_photo_count
    app.lcd.write_string(app.taken_photo_text)[:app.cols]
TypeError: 'NoneType' object is not subscriptable
[ ERROR   ] pibooth           : system='Linux', node='raspberrypi', release='5.4.72-v7+', version='#1356 SMP Thu Oct 22 13:56:54 BST 2020', machine='armv7l', processor=''
 ***********************************************************************************
 *                     Oops! It seems that pibooth has crached                     *
 *     You can report an issue on https://github.com/pibooth/pibooth/issues/new    *
 *                       and post the file: /tmp/pibooth.log                       *

**Comment by werdeil** [comment]
Just pushed a fix, I misplaced two parenthesis...

> But can't see where you get the text from, remaining_duplicates, Printed, forgotten
> maybe that should be from line 178..??

The text from the config are retrieved in the `connect_i2c` method lines 164 to 177, and as this function is only called at startup and when entering the wait state that the reason the change in the config won't be taken into account elsewhere.

**Comment by DJ-Dingo** [comment]
Not working

And something is missing in (or have I overlooked something)
175    # datetime conf part
176    app.show_date_time = cfg.get('LCD_I2C', 'lcd_show_date_time')
177    app.taken_photo_text = cfg.get('LCD_I2C', 'lcd_taken_photo_text')


Should it be 
175    # datetime conf part
176    app.show_date_time = cfg.get('LCD_I2C', 'lcd_show_date_time')

177    # counter text conf part
178    app.taken_photo_text = cfg.get('LCD_I2C', 'lcd_taken_photo_text')
179    app.printed_text = cfg.get('LCD_I2C', 'lcd_printed_text')              
180    app.forgotten_text = cfg.get('LCD_I2C', 'lcd_forgotten_text')              
181    app.remaining_duplicates_text = cfg.get('LCD_I2C', 'lcd_remaining_duplicates_text')              
  

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
[ INFO    ] pibooth           : Installed plugins: picture-template-0.0.3, extra-lights-1.0.1, lcd_i2c_werdeil-1.1.0, sound-effects-0.0.3
[ INFO    ] pibooth           : Starting the photo booth application on Raspberry pi 3B
[ INFO    ] pibooth           : Configuring Picamera camera ...
[ WARNING ] pibooth           : No printer found (pycups or pycups-notify not installed)
[ ERROR   ] pibooth           : Cursor position (0, 16) invalid on a 2x16 LCD.
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pibooth/booth.py", line 343, in main_loop
    self._pm.hook.pibooth_startup(cfg=self._config, app=self)
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/pi/.local/lib/python3.7/site-packages/pibooth/plugins/pibooth_lcd_i2c_werdeil.py", line 189, in pibooth_startup
    write_photo_count(app)
  File "/home/pi/.local/lib/python3.7/site-packages/pibooth/plugins/pibooth_lcd_i2c_werdeil.py", line 82, in write_photo_count
    app.lcd.cursor_pos = (line_index, app.cols)
  File "/usr/local/lib/python3.7/dist-packages/RPLCD/lcd.py", line 155, in _set_cursor_pos
    raise ValueError(msg.format(pos=value, lcd=self.lcd))
ValueError: Cursor position (0, 16) invalid on a 2x16 LCD.
[ ERROR   ] pibooth           : system='Linux', node='raspberrypi', release='5.4.72-v7+', version='#1356 SMP Thu Oct 22 13:56:54 BST 2020', machine='armv7l', processor=''
 ***********************************************************************************
 *                     Oops! It seems that pibooth has crached                     *
 *     You can report an issue on https://github.com/pibooth/pibooth/issues/new    *
 *                       and post the file: /tmp/pibooth.log                       *
 ***********************************************************************************

**Comment by DJ-Dingo** [comment]
app.lcd.cursor_pos = (line_index, app.cols)   - is the problem
If i change it to   app.lcd.cursor_pos = (line_index, 12)  -  it works  ( on a 2x16 lcd )

so to get it to work with any lcd 16 or 20 or ?
You have to have app.cols " - 4"  fot the counter,  to make it work
does that make sence ?

**Comment by werdeil** [comment]
You are completely right:
- I forgot to move some part from the write methods to the connect_i2, I added them
- I misread the principle for the col size, it is indeed app.cols-4 to have the 4 digits to add the rest.

**Comment by DJ-Dingo** [comment]
It works but "Free text" dont need the -4 since it has no counter              app.lcd.write_string(free_text[:app.cols-4])

And it is now moving the counter to the left if you have less text than the 12 or 16 characters you can have in your text with a counter, (on a 16or20 -4 for the counter).

Don't no if it is posibel to have the counter automatic to the right and then have more text showing if the counter is only 1 characters long.
In my version i made it to force the use of 4 characters on the counter to better control it. 
So it could max have "empty space+999" in counter. (after 999 it just move the counter so you dont see the last number)

But dublicates, printed and forgotten will hardly reach that number in the counter.

**Comment by werdeil** [comment]
> It works but "Free text" dont need the -4 since it has no counter app.lcd.write_string(free_text[:app.cols-4])

My bad, did my change too fast, corrected it

> And it is now moving the counter to the left if you have less text than the 12 or 16 characters you can have in your text with a counter, (on a 16or20 -4 for the counter).

Found another issue in my refactoring (the "-4" was also missing in the cursor change), this may correct it.

**Comment by DJ-Dingo** [comment]
Looks like it works (need to test it on an 4x20 lcd i am getting it next week, but it should work)

The Free text don't work. nomally i used Free_Text_1, Free_Text_2, Free_Text_3, Free_Text_4 to get it.
But you only added free_text. so how do it know what freetext it should get on what line?

**Comment by werdeil** [comment]
I was just re-reading it and also found that it should not work...

I just pushed a fix, may this be the last :-)

**Comment by DJ-Dingo** [comment]
Nope, not showing on the screen

**Comment by werdeil** [comment]
Indeed when re-reading it, I see something wrong, I've made another try

**Comment by DJ-Dingo** [comment]
Nope and yes, still not showing.
but if i change Free_Text_{0} to free_text_{0} 
so it is read by  .lower(), then it works... :-) 

But can't change when pibooth is open. i try with app.lcd.clear(), but no.
I will make some tests on that part.

**Comment by werdeil** [comment]
When you say `can't change when pibooth is open` do you mean change the text in the menu and expect it to be updated directly?
If yes this is linked to the `if you change something on the config while pibooth is opened it shall only be taken into account when you re-entrer the wait state` but entering the wait state shall do the update.

**Comment by DJ-Dingo** [comment]
Yes, i then thought it would update the text from config.cfg, after a picture was taken.

**Comment by DJ-Dingo** [comment]
if you change something in config.cfg, save and then go to menu and out, it will update the config.cfg back to what it was before you edited config.cfg.

shoulden it read config.cfg first?
Seems like it is using config.cfg from previous loading

**Comment by werdeil** [comment]
Once pibooth is launched the config shall only be modified through the menu at least this is how we've imagined it. The app will load is at startup, and use only the loaded version. The only time it will use the pibooth.cfg file is when closing the menu to store it (hence having it rewritten).

I'm thinking on (another) refactoring to limit  the number of elements in the config of the plugin, and I'll add the part to add them in the menu so the user can changed the text directly from pibooth

**Comment by DJ-Dingo** [comment]
yeah i understand.

also understand well the part of minimizing elements in config.cfg
I just tested what we have now with a friend who does not have much sense of computer. and he was glad that each line had its own function. I assume you will assemble some of the elements into 1 line, to minimizing config :-)

if you change so it can be changed in the menu which would be nice, it is probably only texts, date-time and which line you want which element on. Since the actual setup part of lcd / I2c, most of the time only needs to be done once.

I have several lcd screens so I will probably make a (lcd_i2c_extra) version, which you can add as an extra plugin in config.cfg if you want to run with 2 lcd's. But since it's just changing all [LCD_I2C] to [LCD_I2C_EXTRA] in the extra version, it should have no effect on the future menu part your adding, it will just add the LCD_I2C_EXTRA to the menu aswell, correct?

**Comment by DJ-Dingo** [comment]
And while we're at it, let's add the footer_text1 and footer_text2 as and options to display aswell

**Pull request merged**
