### PR TITLE
Change the way backlight is disabled at cleanup

### PR DESCRIPTION
**Pull request by werdeil**
I think it is better to avoid generating a new CharLCD object instead of changing a property of the current one.

@DJ-Dingo Can you test if it behaves as your previous code? As I don't have a LCD display I can't test it myself

### CODE REVIEW

**Comment by werdeil** [comment]
@DJ-Dingo tell me if the new changes I made help

**Comment by DJ-Dingo** [comment]
> @DJ-Dingo tell me if the new changes I made help

@werdeil - Had some trouble, one of my lcd was broken, so could not understand why it sometimes worked and other times did not. Got a new lcd now. And i think i had previously installed pibooth, and other programs as sudo, becouse now it says other fails. Updated pibooth, but wont work. Maybe i should install from a fresh Image file and start over, 

File "/home/pi/.local/lib/python3.7/site-packages/pibooth/plugins/pibooth_lcd_i2c.py", line 102, in pibooth_cleanup
    app.lcd.backlight_enabled=False
AttributeError: 'PiApplication' object has no attribute 'lcd'


Here the DEBUG Tmp

[ DEBUG   ] pibooth           : Plugin found at '/home/pi/.local/lib/python3.7/site-packages/pibooth/plugins/pibooth_lcd_i2c.py'
[ INFO    ] pibooth           : Installed plugins: lcd_i2c-1.0.2, extra-lights-1.0.1, sound-effects-0.0.3, picture-template-0.0.3
[ INFO    ] pibooth           : Starting the photo booth application on Raspberry pi 3B
[ INFO    ] pibooth           : Configuring Picamera camera ...
[ WARNING ] pibooth           : No printer found (pycups or pycups-notify not installed)
[ ERROR   ] pibooth           : [Errno 121] Remote I/O error
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pibooth/booth.py", line 343, in main_loop
    self._pm.hook.pibooth_startup(cfg=self._config, app=self)
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/pi/.local/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/pi/.local/lib/python3.7/site-packages/pibooth/plugins/pibooth_lcd_i2c.py", line 35, in pibooth_startup
    app.lcd = CharLCD('PCF8574', 0x3F)
  File "/usr/local/lib/python3.7/dist-packages/RPLCD/i2c.py", line 168, in __init__
    auto_linebreaks=auto_linebreaks)
  File "/usr/local/lib/python3.7/dist-packages/RPLCD/lcd.py", line 103, in __init__
    self.command(0x03)
  File "/usr/local/lib/python3.7/dist-packages/RPLCD/lcd.py", line 381, in command
    self._send_instruction(value)
  File "/usr/local/lib/python3.7/dist-packages/RPLCD/i2c.py", line 241, in _send_instruction
    (value & 0xF0)) | self._backlight)
OSError: [Errno 121] Remote I/O error
[ ERROR   ] pibooth           : system='Linux', node='raspberrypi', release='5.4.51-v7+', version='#1333 SMP Mon Aug 10 16:45:19 BST 2020', machine='armv7l', processor=''
 ***********************************************************************************
 *                     Oops! It seems that pibooth has crached                     *
 *     You can report an issue on https://github.com/pibooth/pibooth/issues/new    *
 *                       and post the file: /tmp/pibooth.log                       *
 ***********************************************************************************

**Comment by werdeil** [comment]
No need to reinstall everything, just remove the pibooth lcd plugin from pibooth as it is the reason of the crash.

**Comment by DJ-Dingo** [comment]
> No need to reinstall everything, just remove the pibooth lcd plugin from pibooth as it is the reason of the crash.

I know. But it was working fine before. unless i had the power off on the I2c-lcd before i start pibooth then no. But if i take power off when pibooth  was running it was  still working fine. So guess i had done something wrong at some point.

**Comment by DJ-Dingo** [comment]
> > No need to reinstall everything, just remove the pibooth lcd plugin from pibooth as it is the reason of the crash.
> 
> I know. But it was working fine before. unless i had the power off on the I2c-lcd before i start pibooth then no. But if i take power off when pibooth was running it was still working fine. So guess i had done something wrong at some point.

**Comment by DJ-Dingo** [comment]
@werdeil,  Okay, it turnt out that 1 of the the wire to the SDA or SCL pin was off.
But that is exactly what i want to prevent from happent, when a wire is gone loose.
Have to test some more.

**Comment by werdeil** [comment]
I reopen as my last changes are preventing this kind of crash: all your call to app.lcd (except the creation of the object) have to be done through try/except to avoid OSError.

**Comment by DJ-Dingo** [comment]
> I reopen as my last changes are preventing this kind of crash: all your call to app.lcd (except the creation of the object) have to be done through try/except to avoid OSError.

Yeah i did close it, by mistake :-) 

This works if the wires are all connected

def i2c(app):
    """test
    """
    try:
        app.lcd = CharLCD('PCF8574', 0x3F, backlight_enabled=True)
    except OSError:
        pass


@pibooth.hookimpl
def pibooth_startup(app):
    i2c(app)


But if one wire is not cennected and try to start pibooth i get
 File "/home/pi/.local/lib/python3.7/site-packages/pibooth/plugins/pibooth_lcd_i2c.py", line 112, in pibooth_cleanup
    app.lcd.backlight_enabled=False
AttributeError: 'PiApplication' object has no attribute 'lcd'

**Comment by werdeil** [comment]
Do you have this in `pibooth_cleanup`?
```
try:
        app.lcd.backlight_enabled=False
        app.lcd.close(clear=True)
except OSError:
        pass
```

**Comment by DJ-Dingo** [comment]
> Do you have this in `pibooth_cleanup`?
> 
> ```
> try:
>         app.lcd.backlight_enabled=False
>         app.lcd.close(clear=True)
> except OSError:
>         pass
> ```



Yes

@pibooth.hookimpl
def pibooth_cleanup(app):
    # Turn off backlight when pibooth close, close lcd screen
    # """ This could be an option as it can be nice to see what time pibooth was shut down
    #     as it stops time and still shows the last time pibooth has been running """
    try:
        app.lcd.backlight_enabled=False
        app.lcd.close(clear=True)
    except OSError:
        pass

**Comment by werdeil** [comment]
Ah my bad, I've found the issue, let me push something new

**Comment by DJ-Dingo** [comment]
> Ah my bad, I've found the issue, let me push something new

ok :-)

**Comment by werdeil** [comment]
Tell me if this new version works

**Comment by DJ-Dingo** [comment]
if hasattr(app, 'lcd'):  
Yes that works if i add it to all them :-) Pibooth is running nomatter what happent to the lcd.

But have a new problem, if i take out a wire, the lcd i stuck, even if i exit and start pibooth again.
Gonna try i restart, too see if this is still happent. 

But most importent pibooth works no matter what, now. :-)

**Comment by DJ-Dingo** [comment]
Okay can't use "if hasattr(app, 'lcd'):"  in my - def i2c(app): i made
otherwise it will be stuck until retstart of pi.
 
but without that If i disconnect a wire now when pibooth is running, it will be stuck there until i restart pibooth, thats better.
Maybe there is a funktion to have it retry to connect lcd after a photo taken.

Better if upload the code that is working for now :-)

**Comment by DJ-Dingo** [comment]
Everything is working fine now, just added  the i2c(app) to the def state_wait_enter(app):
And when wire of, and on it is updated fast and fine after photo taken.
Also Updated the code to ver. 1.0.3. 

@pibooth.hookimpl
def state_wait_enter(app):
    i2c(app)

**Pull request closed without merging**
